//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT_express.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int Id { get; set; }
        public string pic_blog { get; set; }
        public string place_name { get; set; }
        public string city { get; set; }
        public string description { get; set; }
    }
}
