//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT_express.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int Id { get; set; }
        public string c_name { get; set; }
        public string c_email { get; set; }
        public string c_subject { get; set; }
        public string c_message { get; set; }
    }
}
