//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT_express.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tnt_data_model : DbContext
    {
        public tnt_data_model()
            : base("name=tnt_data_model")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bookingdetail> bookingdetails { get; set; }
        public virtual DbSet<bus> buses { get; set; }
        public virtual DbSet<cancelation> cancelations { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<shedule> shedules { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<terminl> terminls { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
    }
}
